ProjectManagementSystem/ProjectManagementSystem/urls.py
from django.contrib import admin
from django.urls import path , include
from management import views

urlpatterns = [
    path('add_developer/', views.add_developer , name='add_developer'),
    path('update_developer/<int:developer_id>' , views.update_developer , name='update_developer' ),
    path('delete_developer/<int:developer_id>', views.delete_developer, name='delete_developer'),

    path('admin/', admin.site.urls),
    path('', views.index , name='index'),
    path('add_project/', views.add_project , name='add_project'),
    path('update_project/<int:project_id>' , views.update_project , name='update_project' ),
    path('delete_project/<int:project_id>', views.delete_project, name='delete_project'),
    path('accounts/', include('accounts.urls')),

]

ProjectManagementSystem/accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

ProjectManagementSystem/accounts/models.py
from django.db import models

# Create your models here.

ProjectManagementSystem/management/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
Status_Catagory = (
    ('Pending', 'Pending'),
    ('Completed', 'Completed'),
    ('to_be_completed','to_be_completed')
)


class Developer(models.Model):
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150)
    email = models.EmailField(blank=True)

    def __str__(self):
        return self.first_name

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=150)
    assigned_to_developer = models.ManyToManyField(Developer)
    start_date = models.DateField(blank=True , null=True)
    end_date = models.DateField(blank=True , null=True)
    status = models.CharField(max_length=30, choices=Status_Catagory, blank=True)
    recorded_at = models.DateTimeField(auto_now_add=True, blank=True)

ProjectManagementSystem/management/forms.py
from django import forms
from .models import Task ,Developer

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ['recorded_at']

class DeveloperForm(forms.ModelForm):
    class Meta:
        model = Developer
        fields = '__all__'

ProjectManagementSystem/accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
# from django.contrib import messages


# @login_required decorator allows to limit access to the index page and check whether the user is authenticated
# if so, index page is rendered. If not, the user is redirected to the login page via login_url

def register_view(request):
    # This function renders the registration form page and create a new user based on the form data
    # We use Django's UserCreationForm which is a model created by Django to create a new user.
    # UserCreationForm has three fields by default: username (from the user model), password1, and password2.
    # If you want to include email as well, switch to our own custom form called UserRegistrationForm

    # Create an instance of the UserCreationForm
    # If there is POST data, populate the form with the provided data,
    # otherwise, create an empty form where Django generates the necessary html on the template.
    form = UserCreationForm(request.POST or None)

    if request.method == 'POST':
        # check whether it's valid: for example it verifies that password1 and password2 match
        if form.is_valid():
            # form.save()
            # if you want to log in the user directly after registration, use the following three lines,
            # which logins the user and redirect to index
            user = form.save()
            login(request, user)
            return redirect('index')
            # if you do want to log in the user directly after registration, comment out the three lines above,
            # redirect the user to login page so that after registration the user can enter the credentials
            # return redirect('login')

    return render(request, 'accounts/register.html', {'form': form})


def login_view(request):
    # this function authenticates the user based on username and password
    # AuthenticationForm is a form for logging a user in.
    # if the request method is a post
    if request.method == 'POST':
        # Plug the request.post in AuthenticationForm
        form = AuthenticationForm(data=request.POST)
        # check whether it's valid:
        if form.is_valid():
            # get the user info from the form data and login the user
            user = form.get_user()
            login(request, user)
            # redirect the user to index page
            return redirect('index')
    else:
        # Create an empty instance of Django's AuthenticationForm to generate the necessary html on the template.
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    # This is the method to log out the user
    logout(request)
    # redirect the user to index page after logout
    return redirect('index')

ProjectManagementSystem/management/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import TaskForm ,DeveloperForm
from .models import Task , Developer
# Create your views here.
def add_developer(request):
    developer_form = DeveloperForm(request.POST or None)
    if developer_form.is_valid():
        developer_form.instance.user = request.user
        task = developer_form.save()
        return redirect('index')
    context = {'form': developer_form}
    return render(request,"add-developer.html",context)

def update_developer(request,developer_id):
    developer = Developer.objects.get(id=developer_id)
    developer_form = DeveloperForm(request.POST or None, instance=developer)
    if developer_form.is_valid():
        developer_form.instance.user = request.user
        developer_form.save()
        return redirect('index')
    context = {'form': developer_form}
    return render(request,"update-developer.html",context)

def delete_developer(request,developer_id):
    developer = Developer.objects.get(id=developer_id)
    developer.delete()
    return redirect('index')
@login_required(login_url='login')
def index(request):
    tasks = Task.objects.filter(user=request.user)
    developers = Developer.objects.all()
    context = {'tasks': tasks, 'developers':developers}
    return render(request,'index.html',context)

def add_project(request):
    task_form = TaskForm(request.POST or None)
    if task_form.is_valid():
        task_form.instance.user = request.user
        task = task_form.save()
        return redirect('index')
    context = {'form': task_form}
    return render(request,"addproject.html",context)

def delete_project(request,project_id):
    task = Task.objects.get(id=project_id,user=request.user)
    task.delete()
    return redirect('index')

def update_project(request,project_id):
    task = Task.objects.get(id=project_id,user=request.user)
    task_form = TaskForm(request.POST or None, instance=task)
    if task_form.is_valid():
        task_form.instance.user = request.user
        task = task_form.save()
        return redirect('index')
    context = {'form': task_form}
    return render(request,"updateproject.html",context)

ProjectManagementSystem/templates/accounts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Font-awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <!-- My own CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>

<!-- I acknowledge that the code below was taken from cs416f23 repository -->
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body fixed-top" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">CS 416</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Page2</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Page3</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Page4</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#"
                           role="button" aria-expanded="false">{{  user.username}}</a>
                        <ul class="dropdown-menu">
                            <li> <a class="dropdown-item" href="{% url 'index' %}">Home</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li> <a class="dropdown-item" href="{% url 'logout' %}">Logout</a> </li>
                        </ul>
                    </li>
                    </ul>

                {% else %}
                    <a class="btn btn-light" href={% url 'login' %}>Login</a>
                    <div class="m-2"></div>
                    <a class="btn btn-light" href={% url 'register' %}>Register</a>
                {% endif %}
        </div>
    </div>
</nav>


<div class="container my-5">
    {% block body %}
    {% endblock %}
</div>


<!-- Bootstrap's JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
</html>

ProjectManagementSystem/templates/accounts/index.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %}
    Index Page
{% endblock %}

{% block body %}

    <section class="container p-5 shadow my-5 bg-body rounded">
        <div class="row align-items-center">
            <div class="col-lg-7">
                <h1 class="display-3 text-sm-start text-center">Hello, {{ user.username }}!</h1>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Aperiam consectetur earum eum nulla, quae soluta.
                    A consequatur cupiditate distinctio dolore facilis fugit, illum porro possimus,
                    sapiente soluta totam voluptate voluptatibus. </p>
                <a class="btn btn-primary btn-lg" href="#" role="button">Do not click me!</a>
            </div>
            <div class="col-lg-5">
                <img src="{% static 'images/undraw_security_o890.png' %}" alt="security_guard" class="img-fluid">
            </div>
        </div>
    </section>

{% endblock %}

ProjectManagementSystem/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Login
{% endblock %}
{% block body %}

    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="display-3 text-center">Login</h1>

                    <!-- Login form -->
                    <form action="{% url 'login' %}" method="post" novalidate>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="d-grid my-4 ">
                            <button class="btn btn-outline-danger btn-lg" type="submit"><i class="fas fa-sign-in-alt"></i> Login</button>
                        </div>
                    </form>


                     <!-- Register link -->
                    <div class="text-center">
                        <p class="small fw-bold my-3 pt-1 mb-0">
                            <a href="{% url 'register' %}" class="link-danger">Register</a>
                        </p>
                    </div>


                </div>
            </div>
        </div>
    </div>

{% endblock %}

ProjectManagementSystem/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Register
{% endblock %}

{% block body %}

    <div class="row justify-content-center">
        <div class="col-8">
            <div class="card">
                <div class="card-body">
                    <h1 class="display-3 text-center">Register</h1>
                    <form action="{% url 'register' %}" method="post" novalidate>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-outline-danger"><i class="fas fa-plus"></i> Register</button>
                    </form>
                </div>
            </div>

        </div>
    </div>


{% endblock %}

ProjectManagementSystem/templates/add-developer.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Add Developer
{% endblock %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="display-3 text-center">Add Developer</h1>
<form action="{% url 'add_developer' %}" method="post"  >
    {% csrf_token %}     
    {{ form|crispy }}

    <input type="submit" value="Add Developer">
</form>
<a href="{% url 'index' %}">Home Page</a>
                    
                </div>
            </div>
        </div>
    </div>

{% endblock %}
</html>

ProjectManagementSystem/templates/addproject.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Add Project
{% endblock %}
{% block body  %}

<!DOCTYPE html>
<html lang="en">
<div class="row justify-content-center" >
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="display-3 text-center">Add Project</h1>
<form action="{% url 'add_project' %}" method="post"  >
    {% csrf_token %}
        {{ form.as_div }}
             <input type="submit" value="Add Project">
    
</form>
                    <a  href="{% url 'index' %}" >Home Page</a>
                     </div>
            </div>
        </div>
    </div>

{% endblock %}
</html>

ProjectManagementSystem/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body style="background-color: antiquewhite">

<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body fixed-top" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Project Manager</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                 <li class="nav-item">
                    <a class="nav-link active"  href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a  class="nav-link active" href="{% url 'add_project' %}">Add New Project</a>
                </li>
                <li class="nav-item">
                    <a  class="nav-link active" href="{% url 'add_developer' %}">Add New Developer</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#"
                           role="button" aria-expanded="false">{{  user.username}}</a>
                        <ul class="dropdown-menu">
                            <li> <a class="dropdown-item" href="{% url 'index' %}">Home</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li> <a class="dropdown-item" href="{% url 'logout' %}">Logout</a> </li>
                        </ul>
                    </li>
                    </ul>

                {% else %}
                    <a class="btn btn-light" href={% url 'login' %}>Login</a>
                    <div class="m-2"></div>
                    <a class="btn btn-light" href={% url 'register' %}>Register</a>
                {% endif %}
        </div>
    </div>
</nav>

<div class="container my-5">
    {% block body %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
</html>

ProjectManagementSystem/templates/index.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body style="background-color: antiquewhite">
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body fixed-top" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Project Manager</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active"  href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a  class="nav-link active" href="{% url 'add_project' %}">Add New Project</a>
                </li>
                <li class="nav-item">
                    <a  class="nav-link active" href="{% url 'add_developer' %}">Add New Developer</a>
                </li>
            
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#"
                           role="button" aria-expanded="false">{{  user.username}}</a>
                        <ul class="dropdown-menu">
                            <li> <a class="dropdown-item" href="{% url 'index' %}">Home</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li> <a class="dropdown-item" href="{% url 'logout' %}">Logout</a> </li>
                        </ul>
                    </li>
                    </ul>

                {% else %}
                    <a class="btn btn-light" href={% url 'login' %}>Login</a>
                    <div class="m-2"></div>
                    <a class="btn btn-light" href={% url 'register' %}>Register</a>
                {% endif %}
        </div>
    </div>
</nav>
    <div class="container py-5 ">
      <div class="row d-flex justify-content-center align-items-center ">
        <div class="col col-lg-11 col-xl-10">
          <div class="card rounded-3">
            <div class="card-body p-4">
              <h4 class="text-center my-3 pb-3">Project Management </h4>
                <div class="col-12">
                   <a  class="btn btn-primary" href="{% url 'add_project' %}">Add New Project</a>
                </div>
                
              <table class="table mb-4">
                <thead>
                  <tr>
                      <th scope="col">#</th>
                    <th scope="col">Project Name</th>
                    <th scope="col">Developers</th>
                    <th scope="col">Start Date</th>
                    <th scope="col">End Date</th>
                    <th scope="col">Status</th>
                    <th scope="col">Recorded</th>
                      <th scope="col">Update</th>
                    <th scope="col">Delete</th>

                  </tr>
                </thead>
                <tbody>
                {% for task in tasks %}
                    
                    
                  <tr >
                  <th>
                    
                        {{ forloop.counter}}
                    </th>
                     	<td>
                             {{ task.name }} 
                        </td>
                         <td>                          
                         {% for developer in task.assigned_to_developer.all %}
                                
                                {{ developer }}
                            {% endfor %}
                        </td>
                         <td>{{ task.start_date }}</td>
                         <td>{{ task.end_date }}</td>
                         <td>{{ task.status }} </td>
                         <td>{{ task.recorded_at }}</td>
                         <td>  <a class="btn btn-warning" href="{% url 'update_project' task.id %}" >Update</a></td>
                         <td>  <a class="btn btn-danger" href="{% url 'delete_project' task.id %}">Delete</a></td>
                   </tr>
                 {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    
        <div class="row d-flex justify-content-center align-items-center my-5 ">
        <div class="col col-lg-11 col-xl-10">
          <div class="card rounded-3">
            <div class="card-body p-4">
              <h4 class="text-center my-3 pb-3">Developer Management </h4>
                <div class="col-12">
                    <a  class="btn btn-primary" href="{% url 'add_developer' %}">Add New Developer</a>
                </div>
                
              <table class="table mb-4">
                <thead>
                  <tr>
                      <th scope="col">#</th>
                    <th scope="col">Developer First Name</th>
                    <th scope="col">Developer Last Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Projects-assigned</th>
                      <th scope="col">Update</th>
                    <th scope="col">Delete</th>
                  </tr>
                </thead>
                <tbody>
                {% for developer in developers %}
                    
                    
                  <tr >
                  <th>
                    
                        {{ forloop.counter}}
                    </th>
                     	<td>
                             {{ developer.first_name }} 
                        </td>
                          <td>{{ developer.last_name }}</td>
                          <td>{{ developer.email }}</td>
                  
                         <td>                          
                         <ul>
                              {% for task in developer.task_set.all %}
                                <li>
                                {{ task.name }}
                             </li>
                            {% endfor %}
                         </ul>
                         
                        </td>
                         <td>  <a class="btn btn-warning" href="{% url 'update_developer' developer.id %}" >Update</a></td>
                         <td>  <a class="btn btn-danger" href="{% url 'delete_developer' developer.id %}" >Delete</a></td>
                   
                  </tr>
                 {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
</html>

ProjectManagementSystem/templates/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
   </head>
<body>
  <div class="wrapper">
    <h2>Login</h2><br>

    {% if messages %}
      {% for message in messages %}
        <h2 style="color: #b22222;">{{message}}</h2>
      {% endfor %}
    {% endif %}
    
    <form action="#" method="POST">
      {% csrf_token %}
      <div class="input-box">
        <input type="text" placeholder="Enter your username" required name="uname">
      </div>
      <div class="input-box">
        <input type="password" placeholder="Enter your password" required name="pass">
      </div>
      <div class="policy">
      </div>
      <div class="input-box button">
        <input type="Submit" value="Login">
      </div>
      <div class="text">
        <h3> <a href="#">Register now</a></h3>
      </div>
      <div class="text">
        <h3> <a href="#">Reset</a></h3>
      </div>
    </form>
  </div>
</body>

<style>
  @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
body{
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #f1f3f9;
}
.wrapper{
  position: relative;
  max-width: 430px;
  width: 100%;
  background: #fff;
  padding: 34px;
  border-radius: 6px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.2);
  margin: 20px;
}
.wrapper h2{
  position: relative;
  font-size: 22px;
  font-weight: 600;
  color: #333;
}
.wrapper h2::before{
  content: '';
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 28px;
  border-radius: 12px;
  background: #4070f4;
}
.wrapper form{
  margin-top: 30px;
}
.wrapper form .input-box{
  height: 52px;
  margin: 18px 0;
}
form .input-box input{
  height: 100%;
  width: 100%;
  outline: none;
  padding: 0 15px;
  font-size: 17px;
  font-weight: 400;
  color: #333;
  border: 1.5px solid #C7BEBE;
  border-bottom-width: 2.5px;
  border-radius: 6px;
  transition: all 0.3s ease;
}
.input-box input:focus,
.input-box input:valid{
  border-color: #4070f4;
}
form .policy{
  display: flex;
  align-items: center;
}
form h3{
  color: #707070;
  font-size: 14px;
  font-weight: 500;
  margin-left: 10px;
}
.input-box.button input{
  color: #fff;
  letter-spacing: 1px;
  border: none;
  background: #4070f4;
  cursor: pointer;
}
.input-box.button input:hover{
  background: #0e4bf1;
}
form .text h3{
 color: #333;
 width: 100%;
 text-align: center;
}
form .text h3 a{
  color: #4070f4;
  text-decoration: none;
}
form .text h3 a:hover{
  text-decoration: underline;
}

</style>
</html>

ProjectManagementSystem/templates/update-developer.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Add Developer
{% endblock %}
{% block body %}

<!DOCTYPE html>
<html lang="en">
<div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="display-3 text-center">Update Developer</h1>
<form action="" method="post"  >
    {% csrf_token %}
      {{ form.as_div }}
        <input type="submit" value="Update Developer">
    
</form>
<a href="{% url 'index' %}">Home Page</a>
                    </div>
            </div>
        </div>
    </div>

{% endblock %}
</html>

ProjectManagementSystem/templates/updateproject.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Add Developer
{% endblock %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="display-3 text-center">Update Project</h1>
<form action=" " method="post"   >
    {% csrf_token %}
    {{ form.as_div }}
            
    <input type="submit" value="Update Project">
</form>
<a href="{% url 'index' %}">Home Page</a>
                     </div>
            </div>
        </div>
    </div>

{% endblock %}
</html>